project_id = "hbtggrbauguukewiknew"

[functions.alvo-proxy]
verify_jwt = false

[functions.alvo-auth]
verify_jwt = false

[functions.proxy-test]
verify_jwt = false

[functions.erp-health-check]
verify_jwt = false

[functions.alvo-sync-worker]
verify_jwt = false

[functions.import-email-nfe-to-compras]
verify_jwt = false

[functions.admin-create-user-fin]
verify_jwt = false

[functions.hub-invite-user]
verify_jwt = false

[functions.notify-aprovador-budget]
verify_jwt = true
