import React, { createContext, useContext, useState, useCallback } from "react";

type Language = "pt" | "en";

const translations = {
  // Sidebar
  "nav.dashboard": { pt: "Dashboard", en: "Dashboard" },
  "nav.cash": { pt: "Caixa e Bancos", en: "Cash & Banks" },
  "nav.receivables": { pt: "Contas a Receber", en: "Accounts Receivable" },
  "nav.sales": { pt: "Receita de Vendas", en: "Sales Revenue" },
  "nav.inventory": { pt: "Estoques", en: "Inventory" },
  "nav.fixed_assets": { pt: "Imobilizado", en: "Fixed Assets" },
  "nav.nf_entrada": { pt: "NF Entrada", en: "Incoming Invoices" },
  "nav.loans": { pt: "Empréstimos", en: "Loans" },
  "nav.taxes": { pt: "Impostos Parcelados", en: "Installment Taxes" },
  "nav.intercompany": { pt: "Intercompany", en: "Intercompany" },
  "nav.credit_cards": { pt: "Cartões de Crédito", en: "Credit Cards" },
  "nav.commodatum": { pt: "Bens em Comodato", en: "Commodatum Assets" },
  "nav.contas_pagar": { pt: "Contas a Pagar", en: "Accounts Payable" },
  "nav.projetos": { pt: "Projetos", en: "Projects" },
  "nav.closing": { pt: "Fechamento", en: "Closing" },
  "nav.entidades": { pt: "Entidades", en: "Entities" },
  "nav.settings": { pt: "Configurações", en: "Settings" },
  "settings.api_connection": { pt: "Conexão API", en: "API Connection" },
  "settings.cost_centers": { pt: "Centros de Custo", en: "Cost Centers" },
  "settings.classes_rec_desp": { pt: "Classes Rec/Desp", en: "Revenue/Expense Classes" },
  "settings.users": { pt: "Usuários", en: "Users" },
  "settings.api_connection_desc": { pt: "Teste a conexão com o ERP Alvo para validar credenciais e acesso.", en: "Test connection with ERP Alvo to validate credentials and access." },
  "settings.test_connection": { pt: "Testar Conexão", en: "Test Connection" },
  "settings.testing": { pt: "Testando...", en: "Testing..." },
  "settings.connected": { pt: "Conectado", en: "Connected" },
  "settings.connection_failed": { pt: "Falha", en: "Failed" },

  // Header
  "header.period": { pt: "Período", en: "Period" },
  "header.logout": { pt: "Sair", en: "Logout" },

  // Auth
  "auth.login": { pt: "Entrar", en: "Sign In" },
  "auth.email": { pt: "Email", en: "Email" },
  "auth.password": { pt: "Senha", en: "Password" },
  "auth.forgot_password": { pt: "Esqueci minha senha", en: "Forgot password" },
  "auth.reset_password": { pt: "Redefinir Senha", en: "Reset Password" },
  "auth.new_password": { pt: "Nova Senha", en: "New Password" },
  "auth.send_reset": { pt: "Enviar link de redefinição", en: "Send reset link" },
  "auth.back_to_login": { pt: "Voltar ao login", en: "Back to login" },
  "auth.reset_sent": { pt: "Link de redefinição enviado! Verifique seu email.", en: "Reset link sent! Check your email." },
  "auth.password_updated": { pt: "Senha atualizada com sucesso!", en: "Password updated successfully!" },
  "auth.error": { pt: "Erro na autenticação", en: "Authentication error" },
  "auth.signing_in": { pt: "Entrando...", en: "Signing in..." },

  // Placeholder
  "placeholder.title": { pt: "Módulo em Construção", en: "Module Under Construction" },
  "placeholder.message": { pt: "Este módulo está sendo desenvolvido e estará disponível em breve.", en: "This module is being developed and will be available soon." },

  // Dashboard
  "dashboard.title": { pt: "Dashboard de Reconciliação", en: "Reconciliation Dashboard" },
  "dashboard.modules_reconciled": { pt: "módulos conciliados", en: "modules reconciled" },
  "dashboard.last_close": { pt: "Último fechamento", en: "Last close" },
  "dashboard.no_close": { pt: "Nenhum fechamento realizado", en: "No close performed" },
  "dashboard.management_balance": { pt: "Saldo Gerencial", en: "Management Balance" },
  "dashboard.accounting_balance": { pt: "Saldo Contábil", en: "Accounting Balance" },
  "dashboard.difference": { pt: "Diferença", en: "Difference" },
  "dashboard.status": { pt: "Status", en: "Status" },
  "dashboard.account": { pt: "Conta", en: "Account" },
  "dashboard.module": { pt: "Módulo", en: "Module" },
  "dashboard.summary_table": { pt: "Tabela Resumo", en: "Summary Table" },
  "dashboard.reconciled": { pt: "Conciliado", en: "Reconciled" },
  "dashboard.justified": { pt: "Justificado", en: "Justified" },
  "dashboard.divergent": { pt: "Divergente", en: "Divergent" },
  "dashboard.view_details": { pt: "Ver detalhes", en: "View details" },
  "dashboard.export": { pt: "Exportar Relatório", en: "Export Report" },
  "dashboard.status_chart": { pt: "Status de Reconciliação", en: "Reconciliation Status" },
  "dashboard.summary_stats": { pt: "Resumo Geral", en: "Overall Summary" },
  "dashboard.overall_progress": { pt: "Progresso Geral de Reconciliação", en: "Overall Reconciliation Progress" },
  "dashboard.close_module": { pt: "Fechar Módulo", en: "Close Module" },
  "dashboard.close_all": { pt: "Fechar Período", en: "Close Period" },
  "dashboard.closed": { pt: "Fechado", en: "Closed" },
  "dashboard.close_confirm": { pt: "Confirmar fechamento?", en: "Confirm closing?" },
  "dashboard.close_confirm_all": { pt: "Fechar todos os módulos elegíveis?", en: "Close all eligible modules?" },
  "dashboard.closed_at": { pt: "Fechado em", en: "Closed at" },
  "dashboard.close_not_eligible": { pt: "Módulo deve estar conciliado ou justificado", en: "Module must be reconciled or justified" },
  "dashboard.close_success": { pt: "Módulo fechado com sucesso!", en: "Module closed successfully!" },
  "dashboard.close_all_success": { pt: "Período fechado com sucesso!", en: "Period closed successfully!" },

  // Module names
  "module.cash": { pt: "Caixa e Bancos", en: "Cash & Banks" },
  "module.receivables": { pt: "Contas a Receber", en: "Accounts Receivable" },
  "module.receivables_interno": { pt: "Clientes Mercado Interno", en: "Domestic Receivables" },
  "module.receivables_externo": { pt: "Clientes Mercado Externo", en: "Foreign Receivables" },
  "module.inventory": { pt: "Estoques", en: "Inventory" },
  "module.fixed_assets": { pt: "Imobilizado", en: "Fixed Assets" },
  "module.suppliers": { pt: "Fornecedores", en: "Suppliers" },
  "module.loans_cp": { pt: "Empréstimos CP", en: "Short-term Loans" },
  "module.loans_lp": { pt: "Empréstimos LP", en: "Long-term Loans" },
  "module.taxes_cp": { pt: "Impostos Parcelados CP", en: "Installment Taxes ST" },
  "module.taxes_lp": { pt: "Impostos Parcelados LP", en: "Installment Taxes LT" },
  "module.intercompany": { pt: "Intercompany", en: "Intercompany" },

  // Receivables
  "recv.title": { pt: "Contas a Receber", en: "Accounts Receivable" },
  "recv.domestic": { pt: "Mercado Interno", en: "Domestic" },
  "recv.foreign": { pt: "Mercado Externo", en: "Foreign" },
  "recv.total": { pt: "Total Clientes", en: "Total Receivables" },
  "recv.aging": { pt: "Aging de Recebíveis", en: "Receivables Aging" },
  "recv.not_due": { pt: "A Vencer", en: "Not Due" },
  "recv.1_30": { pt: "1-30 dias", en: "1-30 days" },
  "recv.31_60": { pt: "31-60 dias", en: "31-60 days" },
  "recv.61_90": { pt: "61-90 dias", en: "61-90 days" },
  "recv.over_90": { pt: "+90 dias", en: "90+ days" },
  "recv.customer": { pt: "Cliente", en: "Customer" },
  "recv.document": { pt: "Nº Documento", en: "Document #" },
  "recv.issue_date": { pt: "Emissão", en: "Issue Date" },
  "recv.due_date": { pt: "Vencimento", en: "Due Date" },
  "recv.currency": { pt: "Moeda", en: "Currency" },
  "recv.original_amount": { pt: "Valor Original", en: "Original Amount" },
  "recv.exchange_rate": { pt: "Câmbio", en: "Exchange Rate" },
  "recv.amount_brl": { pt: "Valor R$", en: "Amount BRL" },
  "recv.market": { pt: "Mercado", en: "Market" },
  "recv.remaining": { pt: "Saldo Restante", en: "Remaining" },
  "recv.add_title": { pt: "Adicionar Título", en: "Add Receivable" },
  "recv.receipt_date": { pt: "Data Recebimento", en: "Receipt Date" },
  "recv.receipt_amount": { pt: "Valor Recebido", en: "Receipt Amount" },
  "recv.notes": { pt: "Observações", en: "Notes" },
  "recv.status.em_aberto": { pt: "Em Aberto", en: "Open" },
  "recv.status.vencido": { pt: "Vencido", en: "Overdue" },
  "recv.status.recebido": { pt: "Recebido", en: "Received" },
  "recv.status.parcial": { pt: "Parcial", en: "Partial" },
  "recv.filter_all": { pt: "Todos", en: "All" },
  "recv.filter_market": { pt: "Mercado", en: "Market" },
  "recv.filter_status": { pt: "Status", en: "Status" },
  "recv.filter_aging": { pt: "Aging", en: "Aging" },

  // Cash & Banks
  "cash.title": { pt: "Caixa e Bancos", en: "Cash & Banks" },
  "cash.bank": { pt: "Banco", en: "Bank" },
  "cash.type": { pt: "Tipo", en: "Type" },
  "cash.type.corrente": { pt: "Depósito à Vista", en: "Checking" },
  "cash.type.aplicacao": { pt: "Aplicação Liquidez Imediata", en: "Short-term Investment" },
  "cash.type.poupanca": { pt: "Poupança", en: "Savings" },
  "cash.account_number": { pt: "Nº Conta", en: "Account #" },
  "cash.statement_balance": { pt: "Saldo Extrato", en: "Statement Balance" },
  "cash.accounting_code": { pt: "Conta Contábil", en: "Accounting Code" },
  "cash.total": { pt: "Total Geral", en: "Grand Total" },
  "cash.add_account": { pt: "Adicionar Conta Bancária", en: "Add Bank Account" },
  "cash.justification": { pt: "Justificativa", en: "Justification" },
  "cash.save": { pt: "Salvar", en: "Save" },
  "cash.cancel": { pt: "Cancelar", en: "Cancel" },
  "cash.edit": { pt: "Editar", en: "Edit" },
  "cash.justify": { pt: "Justificar", en: "Justify" },
  "cash.delete": { pt: "Excluir", en: "Delete" },
  "cash.actions": { pt: "Ações", en: "Actions" },
  "cash.bank_name": { pt: "Nome do Banco", en: "Bank Name" },
  "cash.saved": { pt: "Dados salvos com sucesso!", en: "Data saved successfully!" },
  "cash.deleted": { pt: "Conta excluída com sucesso!", en: "Account deleted successfully!" },
  "cash.reconciliation_status": { pt: "Status de Reconciliação", en: "Reconciliation Status" },

  // Fixed Assets
  "fa.title": { pt: "Imobilizado", en: "Fixed Assets" },
  "fa.asset_values": { pt: "Valores do Ativo", en: "Asset Values" },
  "fa.gross_value": { pt: "Valor Bruto dos Ativos (Custo de Aquisição)", en: "Gross Asset Value (Acquisition Cost)" },
  "fa.depreciation": { pt: "Depreciação Acumulada", en: "Accumulated Depreciation" },
  "fa.net_value": { pt: "Valor Líquido", en: "Net Asset Value" },
  "fa.accounting": { pt: "Contabilidade", en: "Accounting" },
  "fa.source_manual": { pt: "Input Manual", en: "Manual Input" },
  "fa.source_api": { pt: "API Conectada — Última sync", en: "API Connected — Last sync" },
  "fa.configure_api": { pt: "Configurar Integração API", en: "Configure API Integration" },
  "fa.api_url": { pt: "URL do Endpoint", en: "Endpoint URL" },
  "fa.api_key": { pt: "Chave da API", en: "API Key" },
  "fa.sync_frequency": { pt: "Frequência de Sincronização", en: "Sync Frequency" },
  "fa.freq_daily": { pt: "Diária", en: "Daily" },
  "fa.freq_weekly": { pt: "Semanal", en: "Weekly" },
  "fa.freq_monthly": { pt: "Mensal", en: "Monthly" },
  "fa.api_coming_soon": { pt: "Integração via API em desenvolvimento. Os dados são inseridos manualmente nesta versão.", en: "API integration under development. Data is entered manually in this version." },

  // Inventory
  "inv.title": { pt: "Estoques", en: "Inventory" },
  "inv.item_code": { pt: "Código", en: "Code" },
  "inv.description": { pt: "Descrição", en: "Description" },
  "inv.category": { pt: "Categoria", en: "Category" },
  "inv.cat.materia_prima": { pt: "Matéria-Prima", en: "Raw Material" },
  "inv.cat.em_elaboracao": { pt: "Em Elaboração", en: "Work in Progress" },
  "inv.cat.produto_acabado": { pt: "Produto Acabado", en: "Finished Goods" },
  "inv.cat.embalagem": { pt: "Embalagem", en: "Packaging" },
  "inv.cat.outros": { pt: "Outros", en: "Others" },
  "inv.unit": { pt: "Unidade", en: "Unit" },
  "inv.quantity": { pt: "Quantidade", en: "Quantity" },
  "inv.unit_cost": { pt: "Custo Unitário", en: "Unit Cost" },
  "inv.total_cost": { pt: "Custo Total", en: "Total Cost" },
  "inv.location": { pt: "Localização", en: "Location" },
  "inv.loc.almoxarifado": { pt: "Almoxarifado", en: "Warehouse" },
  "inv.loc.producao": { pt: "Produção", en: "Production" },
  "inv.loc.expedicao": { pt: "Expedição", en: "Shipping" },
  "inv.add_item": { pt: "Adicionar Item", en: "Add Item" },
  "inv.physical_total": { pt: "Valor Total Inventário Físico", en: "Total Physical Inventory Value" },
  "inv.import_erp": { pt: "Importar do ERP", en: "Import from ERP" },
  "inv.import_erp_tooltip": { pt: "Integração via API em desenvolvimento", en: "API integration under development" },
  "inv.filter_all": { pt: "Todas", en: "All" },

  // Generic / shared
  "generic.no_entries": { pt: "Nenhum registro encontrado", en: "No entries found" },
  "generic.payment_date": { pt: "Data Pagamento", en: "Payment Date" },
  "generic.payment_amount": { pt: "Valor Pago", en: "Payment Amount" },

  // Taxes / Installments
  "tax.reconciliation": { pt: "Reconciliação Impostos Parcelados", en: "Installment Taxes Reconciliation" },
  "tax.add_plan": { pt: "Adicionar Parcelamento", en: "Add Installment Plan" },
  "tax.plan": { pt: "Parcelamento", en: "Plan" },
  "tax.tax_type": { pt: "Tipo de Imposto", en: "Tax Type" },
  "tax.program": { pt: "Programa", en: "Program" },
  "tax.process": { pt: "Nº do Processo", en: "Process Number" },
  "tax.debt_composition": { pt: "Composição do Débito", en: "Debt Composition" },
  "tax.original_debt": { pt: "Débito Original", en: "Original Debt" },
  "tax.penalty": { pt: "Multa", en: "Penalty" },
  "tax.interest": { pt: "Juros", en: "Interest" },
  "tax.consolidated": { pt: "Débito Consolidado", en: "Consolidated Debt" },
  "tax.installments": { pt: "Parcelas", en: "Installments" },
  "tax.total_installments": { pt: "Total de Parcelas", en: "Total Installments" },
  "tax.paid_installments": { pt: "Parcelas Pagas", en: "Paid Installments" },
  "tax.current_amount": { pt: "Valor Parcela Atual", en: "Current Installment Amount" },
  "tax.update_index": { pt: "Índice de Atualização", en: "Update Index" },
  "tax.balance_total": { pt: "Saldo Devedor Total", en: "Total Outstanding Balance" },
  "tax.balances": { pt: "Saldos Devedores", en: "Outstanding Balances" },
  "tax.dates_status": { pt: "Datas e Status", en: "Dates & Status" },
  "tax.start_date": { pt: "Data Início", en: "Start Date" },
  "tax.next_due": { pt: "Próximo Vencimento", en: "Next Due Date" },
  "tax.progress": { pt: "Progresso", en: "Progress" },
  "tax.schedule": { pt: "Cronograma de Parcelas", en: "Payment Schedule" },
  "tax.add_payment": { pt: "Adicionar Parcela", en: "Add Payment" },
  "tax.principal": { pt: "Principal", en: "Principal" },
  "tax.total": { pt: "Total", en: "Total" },
  "tax.darf": { pt: "Nº DARF/Guia", en: "DARF/Guide #" },
  "tax.st.ativo": { pt: "Ativo", en: "Active" },
  "tax.st.quitado": { pt: "Quitado", en: "Settled" },
  "tax.st.suspenso": { pt: "Suspenso", en: "Suspended" },
  "tax.st.cancelado": { pt: "Cancelado", en: "Cancelled" },
  "tax.pst.a_vencer": { pt: "A Vencer", en: "Upcoming" },
  "tax.pst.pago": { pt: "Pago", en: "Paid" },
  "tax.pst.vencido": { pt: "Vencido", en: "Overdue" },

  // Intercompany
  "ic.title": { pt: "Intercompany", en: "Intercompany" },
  "ic.reconciliation": { pt: "Reconciliação Intercompany", en: "Intercompany Reconciliation" },
  "ic.total_payable": { pt: "Total a Pagar (Passivo)", en: "Total Payable (Liability)" },
  "ic.total_receivable": { pt: "Total a Receber (Ativo)", en: "Total Receivable (Asset)" },
  "ic.tab_companies": { pt: "Por Empresa", en: "By Company" },
  "ic.tab_transactions": { pt: "Transações", en: "Transactions" },
  "ic.company": { pt: "Empresa Relacionada", en: "Related Company" },
  "ic.country": { pt: "País", en: "Country" },
  "ic.type": { pt: "Tipo", en: "Type" },
  "ic.description_label": { pt: "Descrição", en: "Description" },
  "ic.direction_label": { pt: "Direção", en: "Direction" },
  "ic.doc_reference": { pt: "Referência (Contrato/Invoice)", en: "Reference (Contract/Invoice)" },
  "ic.open_items": { pt: "itens em aberto", en: "open items" },
  "ic.payable": { pt: "A Pagar", en: "Payable" },
  "ic.receivable": { pt: "A Receber", en: "Receivable" },
  "ic.net": { pt: "Saldo Líquido", en: "Net Balance" },
  "ic.add_transaction": { pt: "Adicionar Transação", en: "Add Transaction" },
  "ic.tt.emprestimo": { pt: "Empréstimo", en: "Loan" },
  "ic.tt.servico": { pt: "Serviço", en: "Service" },
  "ic.tt.royalty": { pt: "Royalty", en: "Royalty" },
  "ic.tt.reembolso": { pt: "Reembolso", en: "Reimbursement" },
  "ic.tt.outros": { pt: "Outros", en: "Others" },
  "ic.dir.a_pagar": { pt: "A Pagar", en: "Payable" },
  "ic.dir.a_receber": { pt: "A Receber", en: "Receivable" },
  "ic.st.em_aberto": { pt: "Em Aberto", en: "Open" },
  "ic.st.parcial": { pt: "Parcial", en: "Partial" },
  "ic.st.liquidado": { pt: "Liquidado", en: "Settled" },
  "ic.source": { pt: "Origem", en: "Source" },
  "ic.source.manual": { pt: "Manual", en: "Manual" },
  "ic.source.alvo": { pt: "Alvo", en: "Alvo" },
  "ic.doc_type_label": { pt: "Tipo Doc", en: "Doc Type" },
  "ic.doc_number": { pt: "Nº Documento", en: "Document #" },
  "ic.issue_date": { pt: "Data Emissão", en: "Issue Date" },
  "ic.cfop": { pt: "CFOP", en: "CFOP" },
  "ic.invoice_ref": { pt: "Invoice Ref", en: "Invoice Ref" },
  "ic.service_value": { pt: "Valor Serviço", en: "Service Value" },
  "ic.product_value": { pt: "Valor Produto", en: "Product Value" },
  "ic.taxes": { pt: "Impostos", en: "Taxes" },
  "ic.filter_all": { pt: "Todos", en: "All" },
  "ic.total_nfe": { pt: "Total NF-e", en: "Total NF-e" },
  "ic.total_nfse": { pt: "Total NFS-e", en: "Total NFS-e" },
  "ic.total_inv": { pt: "Total INV", en: "Total INV" },
  "ic.tt.exportacao": { pt: "Exportação", en: "Export" },
  "ic.tt.importacao": { pt: "Importação", en: "Import" },

  // Commodatum
  "com.title": { pt: "Bens em Comodato", en: "Commodatum Assets" },
  "com.contract_name": { pt: "Nome do Contrato", en: "Contract Name" },
  "com.start_date": { pt: "Data Início", en: "Start Date" },
  "com.end_date": { pt: "Data Fim", en: "End Date" },
  "com.value": { pt: "Valor", en: "Value" },
  "com.status": { pt: "Status", en: "Status" },
  "com.object": { pt: "Objeto", en: "Object" },
  "com.file": { pt: "Contrato (PDF)", en: "Contract (PDF)" },
  "com.add": { pt: "Adicionar Contrato", en: "Add Contract" },
  "com.st.ativo": { pt: "Ativo", en: "Active" },
  "com.st.encerrado": { pt: "Encerrado", en: "Closed" },
  "com.no_contracts": { pt: "Nenhum contrato cadastrado", en: "No contracts registered" },
  "com.upload": { pt: "Upload do Contrato", en: "Upload Contract" },
  "com.download": { pt: "Baixar", en: "Download" },

  // Months
  "month.1": { pt: "Janeiro", en: "January" },
  "month.2": { pt: "Fevereiro", en: "February" },
  "month.3": { pt: "Março", en: "March" },
  "month.4": { pt: "Abril", en: "April" },
  "month.5": { pt: "Maio", en: "May" },
  "month.6": { pt: "Junho", en: "June" },
  "month.7": { pt: "Julho", en: "July" },
  "month.8": { pt: "Agosto", en: "August" },
  "month.9": { pt: "Setembro", en: "September" },
  "month.10": { pt: "Outubro", en: "October" },
  "month.11": { pt: "Novembro", en: "November" },
  "month.12": { pt: "Dezembro", en: "December" },
} as const;

type TranslationKey = keyof typeof translations;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("pt");

  const t = useCallback(
    (key: TranslationKey) => translations[key]?.[language] ?? key,
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
