// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbtggrbauguukewiknew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhidGdncmJhdWd1dWtld2lrbmV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4OTk5NTMsImV4cCI6MjA5MDQ3NTk1M30.zC8QizNyFYndr7wLObdcAR_OkYJkkbVVCPfJunnEvrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});